### ISSUE TITLE
What to make?

### ISSUE THREAD

**Issue by edwardkenfox** [edwardkenfox/welcome-to-the-genre#1]
Discuss what to make. My random ideas are:

- Virtual currency prediction engine served as a PWA built with Vue.js & a golang server
- npm package usage search engine built with Node.js

**Comment by susumunara** [comment]
Use React or Laravel as front-end part.

**Comment by susumunara** [comment]
What's kind of service we make?
- I wanna make SNS like twitter ,or related to Data Analysis.

**Comment by edwardkenfox** [comment]
-   写真を良い感じにトリミングしてくれる君
-   背景切り取りマン
    -   思い出、その後に
-   SNS
-   フォントうにあった怖い話
-   ロゴロボ
-   ジャンル・ダルク
    -   音楽ジャンル判定機
    -   「あの日聞いた曲のジャンルを僕はまだ知らない」
    -   音源を入力として、rock, hiphop, classical, edm, jazz, r&bくらいを判別してくれる

**Comment by edwardkenfox** [comment]
「音楽ジャンル判定機」で決定
