### ISSUE TITLE
name

### ISSUE THREAD

**Issue by edwardkenfox** [edwardkenfox/welcome-to-the-genre#4]
We need to think the name for this audio genre detecter service. What we have in mind atm are:

- ジャンル・ダルク
- 「あの日聞いた曲のジャンルを僕はまだ知らない」

**Comment by edwardkenfox** [comment]
- genrer
- 音楽ジャンル判定機
- じゃるんnet
- じゃんる.net
- 「オンガクコンニャク〜！」
- genre gate
- music classifier
- 音楽ジャンル うｐだけ（「ブルーレットおくだけ」のリズムで）
- 音楽ナニソーレ
- ジャンルナニコーレ（WEB版）

**Comment by susumunara** [comment]
・Welcome to the genre
・俺のジャンル
・

**Comment by edwardkenfox** [comment]
vote

1. Welcome to the genre
1. あの日聞いた曲のジャンルを僕はまだ知らない

**Comment by susumunara** [comment]
音楽ジャンル うｐだけ
Welcome to the genre

**Comment by edwardkenfox** [comment]
I guess seeing the votes we're gonna go with "Welcome to the genre"
